// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: block.sql

package state

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBlocksFromHeight = `-- name: DeleteBlocksFromHeight :exec
DELETE FROM block WHERE chain_id = $1 AND height >= $2
`

type DeleteBlocksFromHeightParams struct {
	ChainID string `json:"chain_id"`
	Height  int64  `json:"height"`
}

// reorg 롤백 시 orphan 블록 제거 (docs/03 §reorg handleReorg).
func (q *Queries) DeleteBlocksFromHeight(ctx context.Context, arg DeleteBlocksFromHeightParams) error {
	_, err := q.db.Exec(ctx, deleteBlocksFromHeight, arg.ChainID, arg.Height)
	return err
}

const getBlockAtHeight = `-- name: GetBlockAtHeight :one
SELECT chain_id, height, hash, parent_hash, timestamp FROM block WHERE chain_id = $1 AND height = $2
`

type GetBlockAtHeightParams struct {
	ChainID string `json:"chain_id"`
	Height  int64  `json:"height"`
}

// reorg 연속성 검증의 근거 (docs/03 §reorg isContinuous).
func (q *Queries) GetBlockAtHeight(ctx context.Context, arg GetBlockAtHeightParams) (Block, error) {
	row := q.db.QueryRow(ctx, getBlockAtHeight, arg.ChainID, arg.Height)
	var i Block
	err := row.Scan(
		&i.ChainID,
		&i.Height,
		&i.Hash,
		&i.ParentHash,
		&i.Timestamp,
	)
	return i, err
}

const insertBlock = `-- name: InsertBlock :exec
INSERT INTO block (chain_id, height, hash, parent_hash, "timestamp")
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (chain_id, hash) DO NOTHING
`

type InsertBlockParams struct {
	ChainID    string             `json:"chain_id"`
	Height     int64              `json:"height"`
	Hash       string             `json:"hash"`
	ParentHash string             `json:"parent_hash"`
	Timestamp  pgtype.Timestamptz `json:"timestamp"`
}

// ON CONFLICT DO NOTHING: 발행 성공 후 커서 갱신 전에 크래시가 나서 같은 높이를 재처리하더라도
// (chain_id, hash) PK 충돌로 죽지 않고 그대로 재시도할 수 있어야 한다 (FR-16, 멱등 재처리).
func (q *Queries) InsertBlock(ctx context.Context, arg InsertBlockParams) error {
	_, err := q.db.Exec(ctx, insertBlock,
		arg.ChainID,
		arg.Height,
		arg.Hash,
		arg.ParentHash,
		arg.Timestamp,
	)
	return err
}
