// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chain_config.sql

package state

import (
	"context"
)

const getChainConfig = `-- name: GetChainConfig :one
SELECT chain_id, model_type, node_endpoint, node_auth_ref, finality_depth, address_normalization, start_height, enabled FROM chain_config WHERE chain_id = $1
`

func (q *Queries) GetChainConfig(ctx context.Context, chainID string) (ChainConfig, error) {
	row := q.db.QueryRow(ctx, getChainConfig, chainID)
	var i ChainConfig
	err := row.Scan(
		&i.ChainID,
		&i.ModelType,
		&i.NodeEndpoint,
		&i.NodeAuthRef,
		&i.FinalityDepth,
		&i.AddressNormalization,
		&i.StartHeight,
		&i.Enabled,
	)
	return i, err
}

const listEnabledChainConfigs = `-- name: ListEnabledChainConfigs :many
SELECT chain_id, model_type, node_endpoint, node_auth_ref, finality_depth, address_normalization, start_height, enabled FROM chain_config WHERE enabled = true
`

func (q *Queries) ListEnabledChainConfigs(ctx context.Context) ([]ChainConfig, error) {
	rows, err := q.db.Query(ctx, listEnabledChainConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChainConfig
	for rows.Next() {
		var i ChainConfig
		if err := rows.Scan(
			&i.ChainID,
			&i.ModelType,
			&i.NodeEndpoint,
			&i.NodeAuthRef,
			&i.FinalityDepth,
			&i.AddressNormalization,
			&i.StartHeight,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
