// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cursor.sql

package state

import (
	"context"
)

const getCursor = `-- name: GetCursor :one
SELECT chain_id, height FROM cursor WHERE chain_id = $1
`

func (q *Queries) GetCursor(ctx context.Context, chainID string) (Cursor, error) {
	row := q.db.QueryRow(ctx, getCursor, chainID)
	var i Cursor
	err := row.Scan(&i.ChainID, &i.Height)
	return i, err
}

const upsertCursor = `-- name: UpsertCursor :exec
INSERT INTO cursor (chain_id, height) VALUES ($1, $2)
ON CONFLICT (chain_id) DO UPDATE SET height = EXCLUDED.height
`

type UpsertCursorParams struct {
	ChainID string `json:"chain_id"`
	Height  int64  `json:"height"`
}

// 발행 완료 후에만 호출한다 (docs/03 §0 writeCursor, FR-16).
func (q *Queries) UpsertCursor(ctx context.Context, arg UpsertCursorParams) error {
	_, err := q.db.Exec(ctx, upsertCursor, arg.ChainID, arg.Height)
	return err
}
