// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package state

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Block struct {
	ChainID    string             `json:"chain_id"`
	Height     int64              `json:"height"`
	Hash       string             `json:"hash"`
	ParentHash string             `json:"parent_hash"`
	Timestamp  pgtype.Timestamptz `json:"timestamp"`
}

type ChainConfig struct {
	ChainID              string  `json:"chain_id"`
	ModelType            string  `json:"model_type"`
	NodeEndpoint         string  `json:"node_endpoint"`
	NodeAuthRef          *string `json:"node_auth_ref"`
	FinalityDepth        int64   `json:"finality_depth"`
	AddressNormalization string  `json:"address_normalization"`
	StartHeight          int64   `json:"start_height"`
	Enabled              bool    `json:"enabled"`
}

type Cursor struct {
	ChainID string `json:"chain_id"`
	Height  int64  `json:"height"`
}
